# Exercise 3
### Write a Pandas program to filter the records from the world alcohol consumption dataset where the GDP per capita is above 10,000 and the wine servings are greater than 100. Retrieve the country, beer servings, spirit servings, and life expectancy for these filtered records.

In [ ]:
#ex 3 
df.query('gdp_per_capita > 10000 & wine_servings > 100')[['country', 'beer_servings', 'spirit_servings', 'life_expentancy']]

            country  beer_servings  spirit_servings  life_expentancy
5         Argentina          193.0             25.0             76.3
7         Australia          261.0             72.0             82.8
8           Austria          279.0             75.0             81.5
15          Belgium          295.0             84.0             81.1
40          Croatia          230.0             87.0             78.0
42           Cyprus          192.0            154.0             85.0
43          Czechia          361.0            170.0             78.8
44          Denmark          224.0             53.0             86.0
57           France          127.0            151.0             82.4
61          Germany          346.0            117.0             81.0
63           Greece          133.0            112.0             81.0
71          Hungary          234.0            215.0             75.8
77          Ireland          313.0            118.0             81.4
79            Italy           85.0             42.0             82.7
95       Luxembourg          236.0            133.0             82.0
102           Malta          149.0            100.0             81.7
113     Netherlands          251.0             88.0             81.9
114     New Zealand          203.0             79.0             81.6
119          Norway          169.0             71.0             81.8
128        Portugal          194.0             67.0             81.1
140        Slovakia          196.0            293.0             76.7
141        Slovenia          270.0             51.0             88.0
146           Spain          284.0            157.0             82.8
151          Sweden          152.0             60.0             82.4
152     Switzerland          185.0            100.0             83.4
167  United Kingdom          219.0            126.0             81.2
168         Uruguay          115.0             35.0             77.0